language: bash

sudo: required

dist: trusty

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq jq

script:
    - for dir in lists/*/list.json; do echo -n "${dir}: ";jsonschema -i ${dir} schema.json; echo ''; done
